---
title: "Math-Stats II"
author: "Daniel Oluwafemi Olofin"
date: "2025-03-18"
  output: 
    pdf_document:
      latex_engine: xelatex
  geometry: margin = 0.75in
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Question 7e:
```{r}
# Given parameters
n <- 50
p1 <- 1/3
p2 <- 1/3
p3 <- 1/3

# Expected values (mean) of geometric distributions
mu_X <- 1 / p1
mu_Y <- 1 / p2
mu_Z <- 1 / p3

# Variances of geometric distributions
sigma_X2 <- (1 - p1) / p1^2
sigma_Y2 <- (1 - p2) / p2^2
sigma_Z2 <- (1 - p3) / p3^2

# Compute mean and standard deviation of L
E_L <- mu_X + mu_Y + mu_Z
Var_L <- (sigma_X2 / n) + (sigma_Y2 / n) + (sigma_Z2 / n)
SD_L <- sqrt(Var_L)

# Compute P(L ≤ 10) using normal approximation
P_L_10 <- pnorm(10, mean = E_L, sd = SD_L)

# Print the probability
P_L_10
```



# Question 15:

## (i) Probability that the Sample Variance of Company A Exceeds 0.65 Amp

```{r}
pchisq((0.65 * 9 / 0.04), df = 9, lower.tail = FALSE)
```

## (ii) Probability that the Sample Standard Deviation of B is 2/3 Times Larger than That of A

```{r}
pf(4/9, df1 = 14, df2 = 9, lower.tail = FALSE)
```

## (iv) 75th Percentile of the Distribution of S^2a/S2b
```{r}
qf(0.75, df1 = 9, df2 = 14)
```


# Question 17

```{r}
# Load necessary library
library(stats)

# Given parameters
n <- 5  # Sample size
m <- 3  # Binomial parameter (number of trials)
p <- 0.34  # Probability of success

# Compute the probability mass function (pmf) of X ~ Binomial(3, 0.34)
pmf_values <- dbinom(0:m, size = m, prob = p)

# Compute the probability of X_(3) >= 3
# The order statistic X_(3) represents the third largest value in the sample.
# We need to compute P(X_(3) >= 3) = 1 - P(X_(3) <= 2)

# Probability that at most 2 values in the sample are below 3
prob_X3_leq_2 <- sum(dbinom(0:2, size = n, prob = sum(pmf_values[1:3])))

# Probability that X_(3) >= 3
prob_X3_geq_3 <- 1 - prob_X3_leq_2

# Display the result
cat("P(X_(3) >= 3) =", round(prob_X3_geq_3, 4), "\n")

```

